- items:
  - name: base
    content: |
      女性, 二次元少女

  - name: 动物类型
    content: |
      {{rnd(猫,兔子,)}}

  - name: 动物
    content: |
      {{if($动物类型):桌子上有{{$动物类型}}:}}

  - name: 头发
    content: |
      {{rnd(黑,白,红,蓝)}}色头发

- prompts:
  - name: demo
    content: |
      {{base}}，坐在椅子上，{{头发}}, {{动物}}

  - name: demo_cache
    content: |
      {{base}}, 坐在椅子上, {{$头发}}, {{动物}}
      再次提到：{{$动物类型}}和{{$头发}}

  - name: demo_mixed
    content: |
      初始：{{$动物类型}}, {{$头发}}
      重新随机：{{动物类型}}, {{头发}}
      保持缓存：{{$动物类型}}, {{$头发}}

  - name: demo_sub
    items:
      - name: 头发
        content: 白色头发
    content: |
      {{base}}，坐在椅子上，{{头发}}, {{动物}}
